# Generated by Django 4.1.4 on 2023-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин пользователя')),
            ],
            options={
                'verbose_name': 'Разрешенный пользователь',
                'verbose_name_plural': 'Разрешенные пользователи',
            },
        ),
    ]
