# Generated by Django 4.2.2 on 2023-06-09 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alloweduser_user_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLinkedTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Дружественный пользователь')),
                ('user_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дружественный пользователь',
                'verbose_name_plural': 'Дружественные пользователи',
            },
        ),
    ]
