# Generated by Django 4.2.2 on 2023-06-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendlinkedtree'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlinkedtree',
            name='allowed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.alloweduser'),
        ),
    ]
