# Generated by Django 4.2.2 on 2023-06-09 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_friendlinkedtree_allowed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloweduser',
            name='owner_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
