# Generated by Django 4.1.4 on 2022-12-16 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BioPeople',
        ),
    ]
