# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_family_tree:/var/lib/postgresql/data/
    env_file:
      - ./docker-compose.env
    ports:
      - "5432:5432"

  admin:
    build:
      context: ..
      dockerfile: ./deploy/app.Dockerfile
    volumes:
      - media_volume:/usr/src/app/media/
      - static_volume:/usr/src/app/static/
    expose:
      - 8010
    env_file:
      - ./docker-compose.env
    ports:
      - "8010:8000"
    depends_on:
      - db

  celery-default:
    expose:
      - "8000"
    depends_on:
      - admin
      - db
    command: celery -A geneal_tree.celery

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data_family_tree:
  media_volume:
  static_volume: