# Generated by Django 4.1.4 on 2022-12-14 13:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_link', models.ImageField(upload_to='images_peoples/', verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание фотографии')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peoples.people', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Фотография человека',
                'verbose_name_plural': 'Фотографии людей',
            },
        ),
        migrations.CreateModel(
            name='AvatarPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_link', models.ImageField(upload_to='images_peoples/', verbose_name='Аватар человек')),
                ('people', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peoples.people', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Аватар для профиля',
                'verbose_name_plural': 'Аватарки для профилей',
            },
        ),
    ]
