# Generated by Django 3.2.8 on 2021-11-30 13:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_live', models.BooleanField(default=False, null=True, verbose_name='Жив')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='peoples.people')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='RelativePeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_of_kinship', models.CharField(choices=[('SON', 'Сын'), ('DAUGHTER', 'Дочь'), ('MATHER', 'Мать'), ('FATHER', 'Отец'), ('HUSBAND', 'Муж'), ('WIFE', 'Жена')], max_length=50, verbose_name='Степень родства')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peoples.people', verbose_name='Для кого родственник')),
            ],
            options={
                'verbose_name': 'Родственник',
                'verbose_name_plural': 'Родственники',
            },
        ),
        migrations.CreateModel(
            name='PhotoPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_link', models.ImageField(upload_to='media/images_peoples/', verbose_name='Изображение')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peoples.people')),
            ],
            options={
                'verbose_name': 'Фотография человека',
                'verbose_name_plural': 'Фотографии человека',
            },
        ),
        migrations.CreateModel(
            name='BioPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bio', models.TextField(verbose_name='Биография')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peoples.people', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Биография человека',
                'verbose_name_plural': 'Биографии людей',
            },
        ),
    ]
