# Generated by Django 3.2.9 on 2022-01-05 14:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photopeople',
            options={'verbose_name': 'Фотография человека', 'verbose_name_plural': 'Фотография человека'},
        ),
        migrations.AddField(
            model_name='people',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский'), ('NOT_UNDEFINED', 'Не определен')], default='NOT_UNDEFINED', max_length=255, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='people',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peoples.people', verbose_name='Родитель этого человека'),
        ),
        migrations.AlterField(
            model_name='photopeople',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peoples.people', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='photopeople',
            name='photo_link',
            field=models.ImageField(upload_to='images_peoples/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='RelativePeople',
        ),
    ]
