# Generated by Django 3.2.9 on 2022-01-05 14:49

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0002_auto_20220105_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Человек (связь)', 'verbose_name_plural': 'Люди (связи)'},
        ),
        migrations.AlterField(
            model_name='people',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peoples.people', verbose_name='Родитель этого человека (связь)'),
        ),
    ]
